Creating document of Politica de Branches
fga-eps-mds/2018.2-GrupoMDIC pull request #30
Opened 2018-08-30 18:16 UTC by vinicinolivera

# Descrição
Criando politica de branches no docs

# Issue Relacionada
#4 

#

# Tipo de Mudanças

- [ ] Documentação

# Responsáveis pela revisão

@fabiolamfleury (SM)

# Checklist

- [ ] Os commits seguem o padrão de estilo desse projeto.
- [ ] A branch está conforme nossa política.
- [ ] Houve sucesso na integração continua.
- [ ] Os critérios de aceitação foram cumpridos.

2018-08-30 19:45 UTC, fabiolamfleury requested changes
Deixei alguns comentários, por favor de uma olhada :)

2018-08-30 19:45 UTC, fabiolamfleury commented on docs/docs/doc_politica_branches.md
> +    git checkout dev
Se puder trocar dev para develop, pra ficar uniformizado no documento

2018-08-30 19:45 UTC, fabiolamfleury commented on docs/docs/doc_politica_branches.md
> +Para que ocorra uma padronização, nossos commits serão em inglês, com mensagens curtas e que possuam significados relevantes sobre o conteúdo do commit, estes deveão ser feitos apenas quando os incre
Tem um pequeno erro de português em "estes deveão". Além disso, seria legal exemplos da mensagem de commit e como vai ser conjugado o verbo(passado ou particípio)

2018-08-30 19:45 UTC, fabiolamfleury commented on docs/docs/doc_politica_branches.md
> +    Co-authored-by: João Victor <joao15victor08@gmail.com>
Acrescentar tópico de referências

2018-08-30 19:45 UTC, fabiolamfleury commented on docs/docs/doc_politica_branches.md
> +* **Branches documentation** - Essas são as branches na qual são desenvolvidos os documentos do projeto, elas serão criadas com o nome começando **documentation**/ (exemplo: documentation/documentoVi
O pull request da documentação acredito que fica mais adequado para a develop

2018-08-30 19:45 UTC, fabiolamfleury commented on docs/docs/doc_politica_branches.md
> +* **Branches documentation** - Essas são as branches na qual são desenvolvidos os documentos do projeto, elas serão criadas com o nome começando **documentation**/ (exemplo: documentation/documentoVi
exemplo: documentation/documentoVisao o padrão não seria exemplo: documentation/documento-visao

2018-09-05 14:01 UTC, vinicinolivera commented
Foram feitas as devidas atualizações referentes aos comentarios.

2018-09-05 16:37 UTC, fabiolamfleury approved these changes

2018-09-05 16:37 UTC, merged