Creating pipeline DevOps of product
fga-eps-mds/2018.2-GrupoMDIC pull request #65
Opened 2018-09-14 17:13 UTC by vinicinolivera

# Descrição
Criação da pipeline de DevOps

# Issue Relacionada
#50 

# Responsáveis pela revisão

@fabiolamfleury 

# Checklist

- [ ] Os commits seguem o padrão de estilo desse projeto.
- [ ] A branch está conforme nossa política.
- [ ] Houve sucesso na integração continua.
- [ ] Os critérios de aceitação foram cumpridos.
- [ ] Foram realizados testes (sendo o caso) que cobrem as funcionalidades entregues.

2018-09-14 23:35 UTC, fabiolamfleury commented
Conflito no sidebar! De resto ok

2018-09-18 12:03 UTC, fabiolamfleury requested changes
Com qual frequência o ambiente de produção/homologação será atualizado?
Para quem estará disponível o ambiente de homologação?
Como os desenvolvedores vão realizar a entrega dos artefatos criados?
De quantos serviços estamos falando?
Pode haver o surgimento de mais serviços?
Como está previsto o funcionamento da arquitetura do nosso produto de software?




Essas perguntas também devem ser respondidas, (estão no documento de roadmap de deploy contínuo, que citei na issue #50 . Lembrando que nosso ambiente de produção deverá ser atualizado uma vez por sprint ou uma sprint sim e outra não, fica a sua escolha, mas não pode ser a cada funcionalidade entregue! Não vamos jogar as coisas na master diretamente.

2018-09-21 12:52 UTC, vinicinolivera commented
A revisão está sendo feita por mim e pela @SannyaArvelos, subiremos hoje (21/09) uma nova versão do documento com as alterações necessarias

2018-09-21 12:54 UTC, fabiolamfleury commented
Show! 👍

2018-09-22 03:06 UTC, SannyaArvelos commented
Prontinho.

2018-09-23 23:57 UTC, fabiolamfleury approved these changes

2018-09-23 23:57 UTC, merged